"""Seed prototype prompts for training the binary complexity classifier."""

SIMPLE_PROTOTYPES = [
    "What is the capital of France?",
    "Who wrote Romeo and Juliet?",
    "What year did World War II end?",
    "How many continents are there?",
    "What is the chemical symbol for gold?",
    "What language do they speak in Brazil?",
    "Who painted the Mona Lisa?",
    "What is the largest planet in our solar system?",
    "What is the speed of light?",
    "How many sides does a hexagon have?",
    "What is 25 times 4?",
    "Calculate 150 divided by 3",
    "What is 17 plus 38?",
    "What is 10% of 250?",
    "Convert 5 kilometers to miles",
    "Define photosynthesis",
    "What does GDP stand for?",
    "What is an algorithm?",
    "Define the word 'serendipity'",
    "What is a metaphor?",
    "How do you say hello in Japanese?",
    "Translate 'thank you' to Spanish",
    "What is 'goodbye' in French?",
    "Is Python a compiled language?",
    "Does the Earth revolve around the Sun?",
    "Is 7 a prime number?",
    "Can penguins fly?",
    "Is HTML a programming language?",
    "Convert this text to uppercase: hello world",
    "List the days of the week",
    "Sort these numbers: 5, 2, 8, 1, 9",
    "What is today's date?",
    "Reverse the string 'hello'",
    "Hello, how are you?",
    "Good morning!",
    "Tell me a joke",
    "What's your name?",
    "What is the boiling point of water?",
    "What timezone is New York in?",
    "What is the population of Tokyo?",
    "How tall is Mount Everest?",
    "What is the atomic number of carbon?",
    "Summarize this in one sentence",
    "Give me a synonym for 'happy'",
    "What is the opposite of 'cold'?",
    "Name three primary colors",
    "What comes after Tuesday?",
    "Read the file config.yaml",
    "Show me the contents of README.md",
    "What's in the .env file?",
    "List all files in the src directory",
    "Find all Python files in this project",
    "Run npm install",
    "Check the git status",
    "What branch am I on?",
    "Show me the last 5 git commits",
    "Run the tests",
    "Search for the latest version of React",
    "What is the current price of Bitcoin?",
    "Look up the npm package express",
    "Fetch the docs for FastAPI Query parameters",
    "What does this function do?",
    "What's the syntax for a Python list comprehension?",
    "How do I create a new branch in git?",
    "What port is the server running on?",
    "Show me the imports in main.py",
    "Change the port from 3000 to 8080",
    "Add a newline at the end of this file",
    "Rename the variable x to count",
    "Fix this typo: 'recieve' should be 'receive'",
    "Remove the unused import on line 3",
    "What version of Node is installed?",
    "How much disk space is available?",
    "Is the database running?",
    "What's my IP address?",
    "Show the environment variables",
]

MEDIUM_PROTOTYPES = [
    # Focused single-function / single-file work — more than a lookup,
    # less than an architecture. Used by the 3-class DistilBERT classifier.
    "Write a Python function that validates an email address with a regex",
    "Add input validation to this form handler",
    "Write a unit test for this utility function",
    "Convert this callback-based function to use async/await",
    "Add error handling to this file-reading function",
    "Refactor this nested if-else into a switch statement",
    "Write a function that merges two sorted lists",
    "Add type hints to this Python module",
    "Implement a debounce function in JavaScript",
    "Write a SQL query to find the top 10 customers by total order value",
    "Add pagination to this API endpoint",
    "Fix the off-by-one error in this loop",
    "Write a function to deep-clone a nested object",
    "Add a retry wrapper around this HTTP call",
    "Convert this class component to a React hook",
    "Write a regex to extract all URLs from a string",
    "Implement a simple in-memory cache with a TTL",
    "Add logging statements to trace this function's execution",
    "Write a function that parses a CSV row handling quoted fields",
    "Refactor this function to remove the duplicated code",
    "Add a loading state to this React component",
    "Write a migration to add an index on the users.email column",
    "Implement a rate limiter using a token bucket",
    "Fix this failing test — the assertion expects the wrong value",
    "Add a --verbose flag to this CLI script",
    "Write a function to format a duration in seconds as HH:MM:SS",
    "Memoize this expensive recursive function",
    "Add CORS headers to this Express server",
    "Write a function that flattens an arbitrarily nested array",
    "Convert this synchronous file processing to a streaming approach",
    "Implement binary search on a sorted array",
    "Add a database connection pool to this service",
    "Write a function to throttle API calls to N per second",
    "Refactor this God function into three smaller functions",
    "Add JSON schema validation to this request body",
    "Write a Python context manager for a temporary directory",
    "Implement a simple event emitter class",
    "Fix the race condition in this counter increment",
    "Add exponential backoff to this polling loop",
    "Write a function that diffs two objects and returns the changes",
    "Parse this log file and count errors by type",
    "Add a health check endpoint to this FastAPI app",
    "Implement a function to chunk an array into groups of N",
    "Write a decorator that times function execution",
    "Convert this REST endpoint to return paginated results",
]

COMPLEX_PROTOTYPES = [
    "Design a microservices architecture for a real-time multiplayer game with matchmaking, leaderboards, and anti-cheat systems",
    "Architect a distributed event-sourcing system for a financial trading platform that handles millions of transactions per second",
    "Design a scalable notification system that supports push, email, SMS, and in-app channels with user preferences and rate limiting",
    "Create a system design for a URL shortener that handles 100 million daily requests with analytics",
    "Explain the trade-offs between consistency and availability in distributed systems, using real-world examples from companies like Netflix and Amazon",
    "Compare and contrast the CAP theorem implications for SQL vs NoSQL databases in a microservices context, then recommend an approach for an e-commerce platform",
    "Analyze the economic impacts of remote work adoption on urban real estate markets, transportation infrastructure, and local businesses",
    "Walk me through the reasoning behind choosing between a monolithic and microservices architecture for a startup's MVP",
    "Implement a thread-safe LRU cache in Python with TTL support, size limits, and cache statistics tracking",
    "Write a complete REST API with authentication, rate limiting, pagination, and comprehensive error handling using FastAPI",
    "Build a React component library with a design system that includes theming, accessibility, responsive design, and documentation",
    "Implement a B-tree data structure with insert, delete, search, and range query operations, including rebalancing",
    "Create a Python decorator that implements retry logic with exponential backoff, jitter, circuit breaking, and logging",
    "Debug this memory leak in a Node.js application that occurs during WebSocket connections under high concurrency, and explain the GC implications",
    "Optimize this SQL query that takes 30 seconds on a table with 50 million rows, considering indexing strategies, query plan analysis, and partitioning",
    "Profile and optimize a Python data pipeline that processes 10GB CSV files, currently taking 4 hours to complete",
    "Compare the latest transformer architectures (GPT-4, Claude, Gemini, Llama) in terms of training methodology, context handling, and real-world performance benchmarks",
    "Synthesize the current research on quantum error correction and explain the implications for practical quantum computing timelines",
    "Analyze the trade-offs between different consensus algorithms (Paxos, Raft, PBFT) for blockchain applications",
    "Write a short story exploring the ethical implications of AI consciousness, incorporating themes from both Eastern and Western philosophy",
    "Create a detailed fictional world with its own political system, economy, religion, and history spanning 1000 years",
    "Write a technical blog post explaining category theory concepts using cooking metaphors, targeted at software engineers",
    "Prove that the halting problem is undecidable using a diagonalization argument, and explain the practical implications for software verification",
    "Derive the backpropagation algorithm from first principles and explain how automatic differentiation relates to it",
    "Prove the correctness of Dijkstra's algorithm and analyze its time complexity under different priority queue implementations",
    "Design a database schema for a social media platform, then write migration scripts, explain indexing strategy, outline the caching layer, and describe the data archival process",
    "Create a complete CI/CD pipeline configuration including build, test, security scanning, staging deployment, canary releases, and rollback procedures",
    "Build a comprehensive monitoring and alerting system covering application metrics, infrastructure health, business KPIs, and incident response automation",
    "Perform a security audit of this authentication flow, identifying potential vulnerabilities including OWASP Top 10 risks, and recommend mitigations with code examples",
    "Design a zero-trust security architecture for a multi-cloud environment with on-premises legacy systems",
    "Analyze the security implications of implementing OAuth 2.0 with PKCE for a mobile application, including threat modeling",
    "Develop a technical migration strategy to move a monolithic PHP application to a cloud-native architecture, including timeline, risk assessment, and team structure",
    "Create a comprehensive data strategy for a healthcare company transitioning to AI-driven diagnostics, addressing privacy, compliance, and technical infrastructure",
    "Design a disaster recovery plan for a financial services company with RPO of 15 minutes and RTO of 1 hour across multiple regions",
    "Analyze the performance characteristics of different garbage collection algorithms and recommend the optimal GC configuration for a latency-sensitive trading system",
    "Compare container orchestration approaches (Kubernetes, Nomad, ECS) for a company running 500 microservices across three cloud providers",
    "Evaluate the trade-offs of different state management solutions in a large-scale React application with offline-first requirements",
    "Refactor this 2000-line God class into a proper domain-driven design with bounded contexts, aggregates, and event handlers",
    "Review this distributed transaction implementation for correctness, identify race conditions, and propose a saga pattern alternative",
    "Analyze this machine learning pipeline for data leakage, feature engineering issues, and suggest improvements to the model evaluation strategy",
    "Explain how principles from control theory apply to designing auto-scaling systems, with specific implementation recommendations",
    "Connect concepts from game theory to microservices communication patterns and explain how to prevent cascade failures",
    "Apply information theory concepts to optimize data compression in a real-time video streaming architecture",
    "Diagnose why this Kubernetes cluster experiences intermittent pod evictions during peak traffic, analyzing resource limits, node pressure, and scheduler behavior",
    "Investigate a race condition in this concurrent Go program that only manifests under specific timing conditions with high CPU load",
    "Troubleshoot why this distributed cache shows inconsistent reads after network partitions despite using quorum-based replication",
    "Refactor the authentication system from JWT to session-based auth, updating all middleware, routes, and tests across the codebase",
    "Migrate this Express.js app to use TypeScript, converting all files, adding type definitions, and updating the build pipeline",
    "Split this monolithic app.py into a proper package structure with separate modules for routes, models, services, and utils",
    "The deploy is failing in CI — check the GitHub Actions logs, find the error, trace it back to the source file, and fix it",
    "Users are reporting 500 errors on the /api/checkout endpoint — check the logs, reproduce the issue, identify the root cause, and implement a fix",
    "The app is consuming 4GB of memory in production — profile the application, identify the memory leak, and fix it",
    "Read the existing database schema, then implement a new feature for user notifications with migrations, models, API endpoints, and WebSocket support",
    "Look at how authentication works in this codebase, then add OAuth2 login with Google and GitHub providers, including callback handlers and token refresh",
    "Analyze the current test suite, identify gaps in coverage, and write integration tests for all untested API endpoints",
    "Set up a complete development environment: clone the repo, install dependencies, configure the database, run migrations, seed test data, and verify everything works",
    "Create a new microservice that integrates with the existing API gateway — scaffold the project, implement the service, add Docker config, update the gateway routes, and write deployment manifests",
    "Audit all dependencies for security vulnerabilities, update the vulnerable ones, verify no breaking changes, and update the lockfile",
    "Analyze the current database query patterns, identify the N+1 queries, and refactor the ORM layer to use eager loading with proper join strategies",
    "Review the error handling across the entire API, standardize the error response format, add proper error codes, and implement a global exception handler",
    "Evaluate whether we should migrate from REST to GraphQL for this project, analyze the current endpoints, and create a migration plan with schema design",
    "Scrape the documentation site, extract all API endpoints and their parameters, generate TypeScript types, and create an API client library",
    "Monitor this web application for performance regressions — set up Lighthouse CI, configure budgets, and create alerts for Core Web Vitals degradation",
]
